# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        OC\UserBundle\Entity\User: sha512
    #Section qui définit les droit des roles (le role admin possède les droits user)
    role_hierarchy:
        # Un admin hérite des droits d'auteur et de modérateur
        ROLE_ADMIN: [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    #fourni des utilisateurs
    providers:
        main:
            id: fos_user.user_provider.username


    firewalls:
        dev: 
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # on crée un parefeu uniquement pour le formulaire
        main_login:
            #cette expression régulière permet de prendre login mais pas login_check
            pattern: ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            remember_me:
                secret: "%secret%"

    access_control:
           - { path: ^/admin, roles: ROLE_ADMIN }
